
#define PHASH_ALGO	CMPH_BDZ

#define DB_IDX_RECORD_OFFSET	uint64_t
#define DB_IDX_RECORD_LEN	uint32_t
#define DB_IDX_RECORD_NAME	uint16_t
//#define DB_MMAP_FLAGS		(MAP_HUGETLB|MAP_HUGE_2MB)
#define DB_MMAP_FLAGS		0
//(MAP_HUGETLB)
